version: '3'

services:
  web:
    build: .
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
      - publics:/app/public
      - tmps:/app/tmp
      - logs:/app/log
    ports:
      - "3000:3000"

  nginx:
    build: containers/nginx
    volumes:
      - publics:/app/public
      - tmps:/app/tmp
      - logs:/app/log
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  mysql_data:
  tmps:
  logs:
  publics: 