
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['COMIC_FARM_DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  host: <%= ENV['COMIC_FARM_DATABASE_HOST'] %>

development:
  <<: *default
  database: comic_farm_container_db_development

test:
  <<: *default
  database: comic_farm_container_db_test

production:
  <<: *default
  database: comic_farm_production

