
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['COMIC_FARM_DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  host: <%= ENV['COMIC_FARM_DATABASE_HOST'] %>

development:
  <<: *default
  database: comic_farm_container_db_development

test:
  host: localhost
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306
  timeout: 10000
  database: comic_farm_container_db_test
  username: test
  password: test

production:
  <<: *default
  database: comic_farm_production

